
.artifacts-template: &artifacts-template
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
      - i2pd-android-binary/src/main/libs
      #- external/libs/Boost-for-Android-Prebuilt
    expire_in: 1 year
    when: always

.apt-template: &apt-template |
      export LC_ALL=C.UTF-8
      echo Etc/UTC > /etc/timezone
      echo 'quiet "1";' \
           'APT::Install-Recommends "0";' \
           'APT::Install-Suggests "0";' \
           'APT::Acquire::Retries "20";' \
           'APT::Get::Assume-Yes "true";' \
           'Dpkg::Use-Pty "0";' \
        >> /etc/apt/apt.conf.d/99gitlab
      apt-get update
      apt-get dist-upgrade


.android-template: &android-template
  image: ubuntu:latest
  <<: *artifacts-template
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - *apt-template

    - apt-get -qy install
        autoconf
        autogen
        automake
        autopoint
        autotools-dev
        gettext-base
        git
        libtool
        make
        patch
        pkg-config
        ca-certificates
        curl
        gzip
        bzip2
        libtinfo5
        pkg-config
        tar
        unzip
        wget
        g++
        rename

    - rm -rf $PWD/android-ndk*
    - ndk=android-ndk-`echo $CI_JOB_NAME | awk '{print $2}'`
    - ndk_zip=${ndk}-linux-x86_64.zip
    - curl --silent http://dl.google.com/android/repository/${ndk_zip} > $ndk_zip
    - echo "8381C440FE61FCBB01E209211AC01B519CD6ADF51AB1C2281D5DAAD6CA4C8C8C  $ndk_zip" > ${ndk_zip}.sha256
    - sha256sum -c ${ndk_zip}.sha256
    - unzip -q $ndk_zip
    - export ANDROID_NDK_HOME=`pwd`/$ndk

    - export TARGET_I2P_ABI=`echo $CI_JOB_NAME | awk '{print $5}'`
    - export TARGET_I2P_PLATFORM=`echo $CI_JOB_NAME | awk '{print $3}'`

    - mkdir -p external/libs
    - export EXTERNAL_ROOT=`pwd`/external
    - cd external/libs

    - git clone --single-branch --branch OpenSSL_1_1_1h https://github.com/openssl/openssl.git

    - git clone https://github.com/moritz-wundke/Boost-for-Android.git

    - git clone --single-branch --branch miniupnpc_2_2_0 https://github.com/miniupnp/miniupnp.git

    - git clone https://github.com/PurpleI2P/android-ifaddrs.git

    - cd ..

    - git clone --single-branch --branch openssl https://github.com/PurpleI2P/i2pd.git && cd i2pd && git checkout 01df1647bcfe7a9b92a90b457fdf2683e338a4f9 && cd ..


android r20b 16 default armeabi-v7a:
  <<: *android-template
  script:
    - APP_ABI=armeabi-v7a make clean
    - APP_ABI=armeabi-v7a make


android r20b 21 default arm64-v8a:
  <<: *android-template
  script:
    - APP_ABI=arm64-v8a NDK_PLATFORM_LEVEL=21 NDK_BIT=64 make clean
    - APP_ABI=arm64-v8a NDK_PLATFORM_LEVEL=21 NDK_BIT=64 make
